"""GSM8K twin templates.

Each TwinTemplate below was derived directly from the real GSM8K test-set
question at ``gsm8k_index`` (first 60 items) by substituting exact
substrings with named placeholders -- see
scripts/build_templates.py provenance in task-4-report.md for the
construction method. Every template is round-trip verified against the
real dataset text in tests/test_twins.py.

Items from the first 60 GSM8K test records skipped as untemplatable,
with reasons:
  - index 8: multi-stage narrative mixes spelled-word durations ('half-hour') with digit durations that must stay grammatically singular/plural; too fragile to parametrize safely
  - index 12: break-even year count relies on an exact float division (cost / annual profit) plus a +1 'starts earning next year' step; keeping that exact under resampling needs float-tolerant constraints that are too fragile for the generic numeric resampler
  - index 38: solution logic references implicit 'days he doesn't run' derived from a 7-day week that is never stated as a digit or explicit constant in the problem text; can't be re-derived generically from parametrized text
  - index 40: both multipliers ('four times', 'two times') are spelled words and the single free digit (Suzy's age = 1) can't vary without breaking singular/plural agreement in 'is 1 year old'; not enough resamplable freedom to be a meaningful twin
"""

from .verifier import TwinTemplate

TEMPLATES: tuple[TwinTemplate, ...] = (
    TwinTemplate(
        gsm8k_index=0,
        text_template="Janet’s ducks lay {eggs} eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells the remainder at the farmers' market daily for ${price} per fresh duck egg. How much in dollars does she make every day at the farmers' market?",
        param_names=('eggs', 'price'),
        solve_src="def solve(**p):\n    return (p['eggs'] - 3 - 4) * p['price']\n",
        constraints_src="def valid(**p):\n    e, pr = p['eggs'], p['price']\n    return e > 7 and pr > 0 and e < 1000\n",
        original_values={'eggs': 16, 'price': 2},
        original_answer='18',
    ),
    TwinTemplate(
        gsm8k_index=1,
        text_template='A robe takes {blue} bolts of blue fiber and half that much white fiber.  How many bolts in total does it take?',
        param_names=('blue',),
        solve_src="def solve(**p):\n    return p['blue'] + p['blue'] / 2\n",
        constraints_src="def valid(**p):\n    b = p['blue']\n    return b > 0 and b % 2 == 0 and b < 200\n",
        original_values={'blue': 2},
        original_answer='3',
    ),
    TwinTemplate(
        gsm8k_index=2,
        text_template='Josh decides to try flipping a house.  He buys a house for ${buy:,} and then puts in ${repair:,} in repairs.  This increased the value of the house by {pct}%.  How much profit did he make?',
        param_names=('buy', 'repair', 'pct'),
        solve_src="def solve(**p):\n    return p['buy'] * p['pct'] / 100 - p['repair']\n",
        constraints_src="def valid(**p):\n    b, r, pc = p['buy'], p['repair'], p['pct']\n    return (b > 0 and r > 0 and pc > 0 and (b * pc) % 100 == 0\n            and (b * pc / 100 - r) > 0)\n",
        original_values={'buy': 80000, 'repair': 50000, 'pct': 150},
        original_answer='70000',
    ),
    TwinTemplate(
        gsm8k_index=3,
        text_template='James decides to run {sprints} sprints {times_per_week} times a week.  He runs {meters} meters each sprint.  How many total meters does he run a week?',
        param_names=('sprints', 'times_per_week', 'meters'),
        solve_src="def solve(**p):\n    return p['sprints'] * p['times_per_week'] * p['meters']\n",
        constraints_src="def valid(**p):\n    return p['sprints'] > 0 and p['times_per_week'] > 0 and p['meters'] > 0\n",
        original_values={'sprints': 3, 'times_per_week': 3, 'meters': 60},
        original_answer='540',
    ),
    TwinTemplate(
        gsm8k_index=4,
        text_template="Every day, Wendi feeds each of her chickens three cups of mixed chicken feed, containing seeds, mealworms and vegetables to help keep them healthy.  She gives the chickens their feed in three separate meals. In the morning, she gives her flock of chickens {morning} cups of feed.  In the afternoon, she gives her chickens another {afternoon} cups of feed.  How many cups of feed does she need to give her chickens in the final meal of the day if the size of Wendi's flock is {chickens} chickens?",
        param_names=('morning', 'afternoon', 'chickens'),
        solve_src="def solve(**p):\n    total = 3 * p['chickens']\n    return total - p['morning'] - p['afternoon']\n",
        constraints_src="def valid(**p):\n    total = 3 * p['chickens']\n    return p['morning'] > 0 and p['afternoon'] > 0 and total > p['morning'] + p['afternoon']\n",
        original_values={'morning': 15, 'afternoon': 25, 'chickens': 20},
        original_answer='20',
    ),
    TwinTemplate(
        gsm8k_index=5,
        text_template='Kylar went to the store to buy glasses for his new apartment. One glass costs ${price}, but every second glass costs only {discount_pct}% of the price. Kylar wants to buy {n_glasses} glasses. How much does he need to pay for them?',
        param_names=('price', 'discount_pct', 'n_glasses'),
        solve_src="def solve(**p):\n    disc = p['discount_pct'] / 100 * p['price']\n    cheap_n = p['n_glasses'] / 2\n    return cheap_n * disc + cheap_n * p['price']\n",
        constraints_src="def valid(**p):\n    n, pr, dp = p['n_glasses'], p['price'], p['discount_pct']\n    return n > 0 and n % 2 == 0 and pr > 0 and 0 < dp < 100 and (pr * dp) % 100 == 0\n",
        original_values={'price': 5, 'discount_pct': 60, 'n_glasses': 16},
        original_answer='64',
    ),
    TwinTemplate(
        gsm8k_index=6,
        text_template='Toulouse has twice as many sheep as Charleston. Charleston has {mult} times as many sheep as Seattle. How many sheep do Toulouse, Charleston, and Seattle have together if Seattle has {seattle} sheep?',
        param_names=('mult', 'seattle'),
        solve_src="def solve(**p):\n    charleston = p['mult'] * p['seattle']\n    toulouse = 2 * charleston\n    return p['seattle'] + charleston + toulouse\n",
        constraints_src="def valid(**p):\n    return p['mult'] > 0 and p['mult'] < 20 and p['seattle'] > 0 and p['seattle'] < 500\n",
        original_values={'mult': 4, 'seattle': 20},
        original_answer='260',
    ),
    TwinTemplate(
        gsm8k_index=7,
        text_template='Carla is downloading a {size} GB file. Normally she can download {rate} GB/minute, but {pct}% of the way through the download, Windows forces a restart to install updates, which takes {restart} minutes. Then Carla has to restart the download from the beginning. How load does it take to download the file?',
        param_names=('size', 'rate', 'pct', 'restart'),
        solve_src="def solve(**p):\n    partial = p['size'] * p['pct'] / 100\n    t1 = partial / p['rate']\n    t2 = p['size'] / p['rate']\n    return t1 + t2 + p['restart']\n",
        constraints_src="def valid(**p):\n    s, r, pc, rs = p['size'], p['rate'], p['pct'], p['restart']\n    return (s % r == 0 and 0 < pc < 100 and (s * pc / 100) % r == 0\n            and rs > 0 and s > 0 and r > 0)\n",
        original_values={'size': 200, 'rate': 2, 'pct': 40, 'restart': 20},
        original_answer='160',
    ),
    TwinTemplate(
        gsm8k_index=9,
        text_template="Eliza's rate per hour for the first {threshold} hours she works each week is ${rate}. She also receives an overtime pay of {mult} times her regular hourly rate. If Eliza worked for {hours} hours this week, how much are her earnings for this week?",
        param_names=('threshold', 'rate', 'mult', 'hours'),
        solve_src="def solve(**p):\n    ot_hours = p['hours'] - p['threshold']\n    ot_rate = p['rate'] * p['mult']\n    return p['rate'] * p['threshold'] + ot_rate * ot_hours\n",
        constraints_src="def valid(**p):\n    th, r, m, h = p['threshold'], p['rate'], p['mult'], p['hours']\n    return th > 0 and r > 0 and m > 1 and h > th and h < th + 40\n",
        original_values={'threshold': 40, 'rate': 10, 'mult': 1.2, 'hours': 45},
        original_answer='460',
    ),
    TwinTemplate(
        gsm8k_index=10,
        text_template='A new program had {month1} downloads in the first month. The number of downloads in the second month was three times as many as the downloads in the first month, but then reduced by {pct}% in the third month. How many downloads did the program have total over the three months?',
        param_names=('month1', 'pct'),
        solve_src="def solve(**p):\n    m1 = p['month1']\n    m2 = 3 * m1\n    reduction = p['pct'] / 100 * m2\n    m3 = m2 - reduction\n    return m1 + m2 + m3\n",
        constraints_src="def valid(**p):\n    m1, pc = p['month1'], p['pct']\n    m2 = 3 * m1\n    return m1 > 0 and 0 < pc < 100 and (m2 * pc) % 100 == 0\n",
        original_values={'month1': 60, 'pct': 30},
        original_answer='366',
    ),
    TwinTemplate(
        gsm8k_index=11,
        text_template='Toula went to the bakery and bought various types of pastries. She bought {dozens1} dozen donuts which cost ${price1} per dozen, {dozens2} dozen mini cupcakes which cost ${price2} per dozen, and {dozens3} dozen mini cheesecakes for ${price3} per dozen. How much was the total cost?',
        param_names=('dozens1', 'price1', 'dozens2', 'price2', 'dozens3', 'price3'),
        solve_src="def solve(**p):\n    return p['dozens1'] * p['price1'] + p['dozens2'] * p['price2'] + p['dozens3'] * p['price3']\n",
        constraints_src="def valid(**p):\n    return all(p[k] > 0 for k in p) and p['dozens1'] < 30 and p['dozens2'] < 30 and p['dozens3'] < 30\n",
        original_values={'dozens1': 3, 'price1': 68, 'dozens2': 2, 'price2': 80, 'dozens3': 6, 'price3': 55},
        original_answer='694',
    ),
    TwinTemplate(
        gsm8k_index=13,
        text_template='Melanie is a door-to-door saleswoman. She sold a third of her vacuum cleaners at the green house, {red_extra} more to the red house, and half of what was left at the orange house. If Melanie has {final} vacuum cleaners left, how many did she start with?',
        param_names=('red_extra', 'final'),
        solve_src="def solve(**p):\n    before_red = p['final'] * 2 + p['red_extra']\n    return before_red * 3 / 2\n",
        constraints_src="def valid(**p):\n    final, extra = p['final'], p['red_extra']\n    before_red = final * 2 + extra\n    s = before_red * 3 / 2\n    return (final > 0 and extra > 0 and before_red % 2 == 0\n            and s == int(s) and int(s) % 3 == 0 and s < 500)\n",
        original_values={'red_extra': 2, 'final': 5},
        original_answer='18',
    ),
    TwinTemplate(
        gsm8k_index=14,
        text_template='In a dance class of {students} students, {pct1}% enrolled in contemporary dance, {pct2}% of the remaining enrolled in jazz dance, and the rest enrolled in hip-hop dance. What percentage of the entire students enrolled in hip-hop dance?',
        param_names=('students', 'pct1', 'pct2'),
        solve_src="def solve(**p):\n    s, p1, p2 = p['students'], p['pct1'], p['pct2']\n    contemporary = s * p1 / 100\n    remaining = s - contemporary\n    jazz = remaining * p2 / 100\n    hiphop = remaining - jazz\n    return hiphop / s * 100\n",
        constraints_src="def valid(**p):\n    s, p1, p2 = p['students'], p['pct1'], p['pct2']\n    if not (s > 0 and 0 < p1 < 100 and 0 < p2 < 100):\n        return False\n    if (s * p1) % 100 != 0:\n        return False\n    remaining = s - s * p1 / 100\n    if remaining <= 0 or (remaining * p2) % 100 != 0:\n        return False\n    hiphop = remaining - remaining * p2 / 100\n    return (hiphop * 100) % s == 0\n",
        original_values={'students': 20, 'pct1': 20, 'pct2': 25},
        original_answer='60',
    ),
    TwinTemplate(
        gsm8k_index=15,
        text_template='A merchant wants to make a choice of purchase between 2 purchase plans: jewelry worth ${jewelry:,} or electronic gadgets worth ${gadget:,}. His financial advisor speculates that the jewelry market will go up {pct1}% while the electronic gadgets market will rise {pct2}% within the same month. If the merchant is looking to maximize profit at the end of this month by making a choice, how much profit would this be?',
        param_names=('jewelry', 'gadget', 'pct1', 'pct2'),
        solve_src="def solve(**p):\n    profit1 = p['jewelry'] * p['pct1'] / 100\n    profit2 = p['gadget'] * p['pct2'] / 100\n    return max(profit1, profit2)\n",
        constraints_src="def valid(**p):\n    j, g, p1, p2 = p['jewelry'], p['gadget'], p['pct1'], p['pct2']\n    profit1, profit2 = j * p1 / 100, g * p2 / 100\n    return (j > 0 and g > 0 and p1 > 0 and p2 > 0\n            and abs(profit1 - profit2) > 0.01)\n",
        original_values={'jewelry': 5000, 'gadget': 8000, 'pct1': 2.5, 'pct2': 1.2},
        original_answer='125',
    ),
    TwinTemplate(
        gsm8k_index=16,
        text_template="Two trains leave San Rafael at the same time. They begin traveling westward, both traveling for {day1} miles. The next day, they travel northwards, covering {day2} miles. What's the distance covered by each train in the two days?",
        param_names=('day1', 'day2'),
        solve_src="def solve(**p):\n    return p['day1'] + p['day2']\n",
        constraints_src="def valid(**p):\n    return p['day1'] > 0 and p['day2'] > 0\n",
        original_values={'day1': 80, 'day2': 150},
        original_answer='230',
    ),
    TwinTemplate(
        gsm8k_index=17,
        text_template="Jill gets paid ${teach_rate} per hour to teach and ${coach_rate} to be a cheerleading coach. If she works {weeks} weeks a year, {teach_hours} hours a week as a teacher and {coach_hours} hours a week as a coach, what's her annual salary?",
        param_names=('teach_rate', 'coach_rate', 'weeks', 'teach_hours', 'coach_hours'),
        solve_src="def solve(**p):\n    return (p['teach_rate'] * p['teach_hours'] + p['coach_rate'] * p['coach_hours']) * p['weeks']\n",
        constraints_src="def valid(**p):\n    return all(p[k] > 0 for k in p) and p['weeks'] < 60\n",
        original_values={'teach_rate': 20, 'coach_rate': 30, 'weeks': 50, 'teach_hours': 35, 'coach_hours': 15},
        original_answer='57500',
    ),
    TwinTemplate(
        gsm8k_index=18,
        text_template='Claire makes a {eggs} egg omelet every morning for breakfast.  How many dozens of eggs will she eat in {weeks} weeks?',
        param_names=('eggs', 'weeks'),
        solve_src="def solve(**p):\n    total_eggs = p['eggs'] * 7 * p['weeks']\n    return total_eggs / 12\n",
        constraints_src="def valid(**p):\n    e, w = p['eggs'], p['weeks']\n    return e > 0 and w > 0 and (e * 7 * w) % 12 == 0\n",
        original_values={'eggs': 3, 'weeks': 4},
        original_answer='7',
    ),
    TwinTemplate(
        gsm8k_index=19,
        text_template='Marissa is hiking a {dist_total}-mile trail. She took 1 hour to walk the first {dist1} miles, then another hour to walk the next two miles. If she wants her average speed to be {avg_speed} miles per hour, what speed (in miles per hour) does she need to walk the remaining distance?',
        param_names=('dist_total', 'dist1', 'avg_speed'),
        solve_src="def solve(**p):\n    total_time = p['dist_total'] / p['avg_speed']\n    remaining_time = total_time - 2\n    remaining_dist = p['dist_total'] - p['dist1'] - 2\n    return remaining_dist / remaining_time\n",
        constraints_src="def valid(**p):\n    dt, d1, sp = p['dist_total'], p['dist1'], p['avg_speed']\n    if not (dt > d1 + 2 > 0 and sp > 0 and dt % sp == 0):\n        return False\n    rt = dt / sp - 2\n    rd = dt - d1 - 2\n    return rt > 0 and rd % rt == 0\n",
        original_values={'dist_total': 12, 'dist1': 4, 'avg_speed': 4},
        original_answer='6',
    ),
    TwinTemplate(
        gsm8k_index=20,
        text_template='I have {vol1} liters of orange drink that are two-thirds water and I wish to add it to {vol2} liters of pineapple drink that is three-fifths water. But as I pour it, I spill one liter of the orange drink. How much water is in the remaining {remaining} liters?',
        param_names=('vol1', 'vol2'),
        solve_src="def solve(**p):\n    water_pine = p['vol2'] * 3 / 5\n    orange_after_spill = p['vol1'] - 1\n    water_orange = orange_after_spill * 2 / 3\n    return water_pine + water_orange\n",
        constraints_src="def valid(**p):\n    v1, v2 = p['vol1'], p['vol2']\n    if not (v1 > 1 and v2 > 0 and v2 % 5 == 0 and (v1 - 1) % 3 == 0):\n        return False\n    return True\n",
        # "the remaining 24 liters" is a derived literal: 24 = vol1 + vol2 - 1
        # (total poured minus the spilled liter). Computed, never resampled.
        derived_src="def derive(**p):\n    return {'remaining': p['vol1'] + p['vol2'] - 1}\n",
        original_values={'vol1': 10, 'vol2': 15, 'remaining': 24},
        original_answer='15',
    ),
    TwinTemplate(
        gsm8k_index=21,
        text_template="Raymond and Samantha are cousins. Raymond was born {gap} years before Samantha. Raymond had a son at the age of {son_age}. If Samantha is now {samantha_now}, how many years ago was Raymond's son born?",
        param_names=('gap', 'son_age', 'samantha_now'),
        solve_src="def solve(**p):\n    samantha_then = p['son_age'] - p['gap']\n    return p['samantha_now'] - samantha_then\n",
        constraints_src="def valid(**p):\n    g, sa, sn = p['gap'], p['son_age'], p['samantha_now']\n    samantha_then = sa - g\n    return g > 0 and sa > g and sn > samantha_then > 0\n",
        original_values={'gap': 6, 'son_age': 23, 'samantha_now': 31},
        original_answer='14',
    ),
    TwinTemplate(
        gsm8k_index=22,
        text_template="Billy sells DVDs. He has {total_customers} customers on Tuesday. His first {c1} customers buy one DVD each.  His next {c2} customers buy {dvd2} DVDs each.  His last {c3} customers don't buy any DVDs. How many DVDs did Billy sell on Tuesday?",
        param_names=('c1', 'c2', 'dvd2', 'c3'),
        solve_src="def solve(**p):\n    return p['c1'] * 1 + p['c2'] * p['dvd2'] + p['c3'] * 0\n",
        constraints_src="def valid(**p):\n    return p['c1'] > 0 and p['c2'] > 0 and p['c3'] > 0 and p['dvd2'] > 0 and p['dvd2'] < 20\n",
        # "He has 8 customers" is a derived literal: 8 = c1 + c2 + c3.
        # Computed from the resampled group sizes, never resampled itself.
        derived_src="def derive(**p):\n    return {'total_customers': p['c1'] + p['c2'] + p['c3']}\n",
        original_values={'c1': 3, 'c2': 2, 'dvd2': 2, 'c3': 3, 'total_customers': 8},
        original_answer='7',
    ),
    TwinTemplate(
        gsm8k_index=23,
        text_template='A candle melts by {rate} centimeters every hour that it burns. How many centimeters shorter will a candle be after burning from {start}:00 PM to {end}:00 PM?',
        param_names=('rate', 'start', 'end'),
        solve_src="def solve(**p):\n    return (p['end'] - p['start']) * p['rate']\n",
        constraints_src="def valid(**p):\n    r, s, e = p['rate'], p['start'], p['end']\n    return r > 0 and 1 <= s < e <= 12\n",
        original_values={'rate': 2, 'start': 1, 'end': 5},
        original_answer='8',
    ),
    TwinTemplate(
        gsm8k_index=24,
        text_template="Kyle bought last year's best-selling book for ${paid:.2f}. This is with a {discount_pct}% discount from the original price. What was the original price of the book?",
        param_names=('paid', 'discount_pct'),
        solve_src="def solve(**p):\n    return p['paid'] / (1 - p['discount_pct'] / 100)\n",
        constraints_src="def valid(**p):\n    pa, dp = p['paid'], p['discount_pct']\n    if not (pa > 0 and 0 < dp < 100):\n        return False\n    orig = pa / (1 - dp / 100)\n    return abs(orig - round(orig, 2)) < 1e-9\n",
        original_values={'paid': 19.5, 'discount_pct': 25},
        original_answer='26',
    ),
    TwinTemplate(
        gsm8k_index=25,
        text_template='Marie ordered one chicken meal that costs ${meal}, {milk_n} packs of milk that costs ${milk_price} each, {apple_n} apples that cost ${apple_price:.2f} each, and some boxes of pizza. Marie paid a total of ${total_paid}. How many boxes of pizza did Marie order if each box costs ${pizza_price:.2f}?',
        param_names=('meal', 'milk_n', 'milk_price', 'apple_n', 'apple_price', 'total_paid', 'pizza_price'),
        solve_src="def solve(**p):\n    spent = p['meal'] + p['milk_n'] * p['milk_price'] + p['apple_n'] * p['apple_price']\n    remaining = p['total_paid'] - spent\n    return remaining / p['pizza_price']\n",
        constraints_src="def valid(**p):\n    m, mn, mp, an, ap, tp, pp = (p['meal'], p['milk_n'], p['milk_price'],\n                                 p['apple_n'], p['apple_price'], p['total_paid'], p['pizza_price'])\n    spent = m + mn * mp + an * ap\n    remaining = tp - spent\n    if remaining <= 0:\n        return False\n    boxes = remaining / pp\n    return abs(boxes - round(boxes)) < 1e-9 and all(v > 0 for v in p.values())\n",
        original_values={'meal': 12, 'milk_n': 5, 'milk_price': 3, 'apple_n': 4, 'apple_price': 1.5, 'total_paid': 50, 'pizza_price': 8.5},
        original_answer='2',
    ),
    TwinTemplate(
        gsm8k_index=26,
        text_template='Mishka bought {n} pairs of shorts, {n} pairs of pants, and {n} pairs of shoes. One pair of shorts costs ${shorts:.2f}. One pair of pants costs ${pants:.2f} and one pair of shoes costs ${shoes}. How many dollars did Mishka spend on all the clothing items?',
        param_names=('n', 'shorts', 'pants', 'shoes'),
        solve_src="def solve(**p):\n    return p['n'] * (p['shorts'] + p['pants'] + p['shoes'])\n",
        constraints_src="def valid(**p):\n    return p['n'] > 0 and p['n'] < 20 and all(p[k] > 0 for k in ('shorts', 'pants', 'shoes'))\n",
        original_values={'n': 3, 'shorts': 16.5, 'pants': 22.5, 'shoes': 42},
        original_answer='243',
    ),
    TwinTemplate(
        gsm8k_index=27,
        text_template='Cynthia eats one serving of ice cream every night.  She buys cartons of ice cream with {servings} servings of ice cream per carton at a cost of ${price:.2f} per carton.  After {days} days, how much will she spend on ice cream?',
        param_names=('servings', 'price', 'days'),
        solve_src="def solve(**p):\n    cartons = p['days'] / p['servings']\n    return cartons * p['price']\n",
        constraints_src="def valid(**p):\n    d, sv, pr = p['days'], p['servings'], p['price']\n    return d > 0 and sv > 0 and pr > 0 and d % sv == 0\n",
        original_values={'servings': 15, 'price': 4, 'days': 60},
        original_answer='16',
    ),
    TwinTemplate(
        gsm8k_index=28,
        text_template='Henry made two stops during his {total}-mile bike trip. He first stopped after {stop1} miles. His second stop was {stop2} miles before the end of the trip. How many miles did he travel between his first and second stops?',
        param_names=('total', 'stop1', 'stop2'),
        solve_src="def solve(**p):\n    return p['total'] - p['stop1'] - p['stop2']\n",
        constraints_src="def valid(**p):\n    t, s1, s2 = p['total'], p['stop1'], p['stop2']\n    return s1 > 0 and s2 > 0 and t > s1 + s2\n",
        original_values={'total': 60, 'stop1': 20, 'stop2': 15},
        original_answer='25',
    ),
    TwinTemplate(
        gsm8k_index=29,
        text_template='Gloria is shoe shopping when she comes across a pair of boots that fit her shoe budget. However, she has to choose between the boots and two pairs of high heels that together cost five dollars less than the boots. If one pair of heels costs ${heel1} and the other costs twice as much, how many dollars are the boots?',
        param_names=('heel1',),
        solve_src="def solve(**p):\n    heel2 = 2 * p['heel1']\n    return p['heel1'] + heel2 + 5\n",
        constraints_src="def valid(**p):\n    return p['heel1'] > 0 and p['heel1'] < 10000\n",
        original_values={'heel1': 33},
        original_answer='104',
    ),
    TwinTemplate(
        gsm8k_index=30,
        text_template="Darrell and Allen's ages are in the ratio of {r1}:{r2}. If their total age now is {total}, calculate Allen's age {years} years from now.",
        param_names=('r1', 'r2', 'total', 'years'),
        solve_src="def solve(**p):\n    r1, r2, tot, yrs = p['r1'], p['r2'], p['total'], p['years']\n    allen = tot * r2 / (r1 + r2)\n    return allen + yrs\n",
        constraints_src="def valid(**p):\n    r1, r2, tot, yrs = p['r1'], p['r2'], p['total'], p['years']\n    return r1 > 0 and r2 > 0 and tot > 0 and yrs > 0 and tot % (r1 + r2) == 0\n",
        original_values={'r1': 7, 'r2': 11, 'total': 162, 'years': 10},
        original_answer='109',
    ),
    TwinTemplate(
        gsm8k_index=31,
        text_template='Gunter is trying to count the jelly beans in a jar. He asks his friends how many they think are in the jar. One says {g1}. Another says {extra} more than half the first one. A third says {pct}% more than the first one. What is their average guess?',
        param_names=('g1', 'extra', 'pct'),
        solve_src="def solve(**p):\n    g1, extra, pct = p['g1'], p['extra'], p['pct']\n    g2 = extra + g1 / 2\n    g3 = g1 * (1 + pct / 100)\n    return (g1 + g2 + g3) / 3\n",
        constraints_src="def valid(**p):\n    g1, extra, pct = p['g1'], p['extra'], p['pct']\n    if not (g1 > 0 and g1 % 2 == 0 and extra > 0 and pct > 0 and (g1 * pct) % 100 == 0):\n        return False\n    g2 = extra + g1 / 2\n    g3 = g1 * (1 + pct / 100)\n    return (g1 + g2 + g3) % 3 == 0\n",
        original_values={'g1': 80, 'extra': 20, 'pct': 25},
        original_answer='80',
    ),
    TwinTemplate(
        gsm8k_index=32,
        text_template='John takes care of {n} dogs.  Each dog takes .5 hours a day to walk and take care of their business.  How many hours a week does he spend taking care of dogs?',
        param_names=('n',),
        solve_src="def solve(**p):\n    return p['n'] * 0.5 * 7\n",
        constraints_src="def valid(**p):\n    return p['n'] > 0 and p['n'] < 100\n",
        original_values={'n': 10},
        original_answer='35',
    ),
    TwinTemplate(
        gsm8k_index=33,
        text_template='Gretchen has {total} coins. There are {diff} more gold coins than silver coins. How many gold coins does Gretchen have?',
        param_names=('total', 'diff'),
        solve_src="def solve(**p):\n    silver = (p['total'] - p['diff']) / 2\n    return silver + p['diff']\n",
        constraints_src="def valid(**p):\n    t, d = p['total'], p['diff']\n    return t > d > 0 and (t - d) % 2 == 0\n",
        original_values={'total': 110, 'diff': 30},
        original_answer='70',
    ),
    TwinTemplate(
        gsm8k_index=34,
        text_template="Siobhan has {diff1} fewer jewels than Aaron. Aaron has {diff2} more jewels than half of Raymond's jewels. If Raymond has {raymond} jewels, how many jewels does Siobhan have?",
        param_names=('diff1', 'diff2', 'raymond'),
        solve_src="def solve(**p):\n    half = p['raymond'] / 2\n    aaron = half + p['diff2']\n    return aaron - p['diff1']\n",
        constraints_src="def valid(**p):\n    d1, d2, r = p['diff1'], p['diff2'], p['raymond']\n    if not (r > 0 and r % 2 == 0 and d1 > 0 and d2 > 0):\n        return False\n    aaron = r / 2 + d2\n    return aaron - d1 > 0\n",
        original_values={'diff1': 2, 'diff2': 5, 'raymond': 40},
        original_answer='23',
    ),
    TwinTemplate(
        gsm8k_index=35,
        text_template='Mike plays ping pong for {total} minutes.  In the first {block1} minutes, he scores {points1} points.  In the second {block2} minutes, he scores {pct}% more points.  How many total points did he score?',
        param_names=('block1', 'block2', 'points1', 'pct'),
        solve_src="def solve(**p):\n    extra = p['points1'] * p['pct'] / 100\n    points2 = p['points1'] + extra\n    return p['points1'] + points2\n",
        constraints_src="def valid(**p):\n    p1, pct = p['points1'], p['pct']\n    return p1 > 0 and pct > 0 and (p1 * pct) % 100 == 0 and p['block1'] > 0 and p['block2'] > 0\n",
        # "plays ping pong for 40 minutes" is a derived literal: 40 = the sum
        # of the two block durations (both 20 in the original). Both blocks
        # are now free params; the total is computed, never resampled.
        derived_src="def derive(**p):\n    return {'total': p['block1'] + p['block2']}\n",
        original_values={'block1': 20, 'block2': 20, 'points1': 4, 'pct': 25, 'total': 40},
        original_answer='9',
    ),
    TwinTemplate(
        gsm8k_index=36,
        text_template='Terry eats {per_day} yogurts a day.  They are currently on sale at {pack_n} yogurts for ${pack_price:.2f}.  How much does he spend on yogurt over {days} days?',
        param_names=('per_day', 'pack_n', 'pack_price', 'days'),
        solve_src="def solve(**p):\n    total_yogurts = p['per_day'] * p['days']\n    packs = total_yogurts / p['pack_n']\n    return packs * p['pack_price']\n",
        constraints_src="def valid(**p):\n    pd, pn, days = p['per_day'], p['pack_n'], p['days']\n    return pd > 0 and pn > 0 and days > 0 and (pd * days) % pn == 0\n",
        original_values={'per_day': 2, 'pack_n': 4, 'pack_price': 5, 'days': 30},
        original_answer='75',
    ),
    TwinTemplate(
        gsm8k_index=37,
        text_template='John plans to sell all his toys and use the money to buy video games. He has {n_sets} lego sets and he sells them for ${price} each. He ends up buying {n_games} video games for ${game_price} each and has ${leftover} left. How many lego sets does he still have?',
        param_names=('n_sets', 'price', 'n_games', 'game_price', 'leftover'),
        solve_src="def solve(**p):\n    spent = p['n_games'] * p['game_price']\n    earned = spent + p['leftover']\n    sold = earned / p['price']\n    return p['n_sets'] - sold\n",
        constraints_src="def valid(**p):\n    ns, pr, ng, gp, lo = p['n_sets'], p['price'], p['n_games'], p['game_price'], p['leftover']\n    earned = ng * gp + lo\n    if earned % pr != 0:\n        return False\n    sold = earned / pr\n    return 0 < sold < ns\n",
        original_values={'n_sets': 13, 'price': 15, 'n_games': 8, 'game_price': 20, 'leftover': 5},
        original_answer='2',
    ),
    TwinTemplate(
        gsm8k_index=39,
        text_template='Dana can run at a rate of speed four times faster than she can walk, but she can skip at a rate of speed that is half as fast as she can run. If she can skip at {skip_speed} miles per hour, how many miles can she travel in six hours if she spends one-third of the time running and two-thirds of the time walking?',
        param_names=('skip_speed',),
        solve_src="def solve(**p):\n    run_speed = p['skip_speed'] * 2\n    walk_speed = run_speed / 4\n    run_time = 6 / 3\n    walk_time = 6 - run_time\n    return run_time * run_speed + walk_time * walk_speed\n",
        constraints_src="def valid(**p):\n    return p['skip_speed'] > 0 and p['skip_speed'] < 100\n",
        original_values={'skip_speed': 3},
        original_answer='18',
    ),
    TwinTemplate(
        gsm8k_index=41,
        text_template="The great dragon, Perg, sat high atop mount Farbo, breathing fire upon anything within a distance of {range} feet.  Polly could throw the gold javelin, the only known weapon that could sleigh the dragon, for a distance of {dist} feet, well within the reach of the dragon's flames.  But when Polly held the sapphire gemstone, she could throw the javelin three times farther than when not holding the gemstone. If holding the gemstone, how far outside of the reach of the dragon's flames could Polly stand and still hit the dragon with the gold javelin?",
        param_names=('range', 'dist'),
        solve_src="def solve(**p):\n    boosted = p['dist'] * 3\n    return boosted - p['range']\n",
        constraints_src="def valid(**p):\n    r, d = p['range'], p['dist']\n    return d > 0 and r > 0 and d < r and d * 3 > r\n",
        original_values={'range': 1000, 'dist': 400},
        original_answer='200',
    ),
    TwinTemplate(
        gsm8k_index=42,
        text_template="Grandma Jones baked {n_pies} apple pies for the fireman's luncheon.  She cut each pie into {pieces} pieces and set the {n_pies_word} pies out on the buffet table for the guests to serve themselves.  At the end of the evening, after the guests had taken and eaten their pieces of pie, there were {remaining} pieces of pie remaining.  How many pieces were taken by the guests?",
        param_names=('n_pies', 'pieces', 'n_pies_word', 'remaining'),
        solve_src="def solve(**p):\n    total = p['n_pies'] * p['pieces']\n    return total - p['remaining']\n",
        constraints_src="def valid(**p):\n    words = {'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5,\n             'six': 6, 'seven': 7, 'eight': 8, 'nine': 9, 'ten': 10, 'eleven': 11,\n             'twelve': 12, 'thirteen': 13, 'fourteen': 14, 'fifteen': 15,\n             'sixteen': 16, 'twenty': 20, 'thirty': 30}\n    n, pc, rem, nw = p['n_pies'], p['pieces'], p['remaining'], p['n_pies_word']\n    total = n * pc\n    return rem > 0 and total > rem and words.get(nw) == n\n",
        original_values={'n_pies': 5, 'pieces': 8, 'n_pies_word': 'five', 'remaining': 14},
        original_answer='26',
    ),
    TwinTemplate(
        gsm8k_index=43,
        text_template='According to its nutritional info, a bag of chips has {cal} calories per serving. If a {bag}g bag has {servings} servings, how many grams can you eat if your daily calorie target is {target} and you have already consumed {consumed} calories?',
        param_names=('cal', 'bag', 'servings', 'target', 'consumed'),
        solve_src="def solve(**p):\n    cal, bag, sv, target, cons = (p['cal'], p['bag'], p['servings'],\n                                   p['target'], p['consumed'])\n    remaining_cal = target - cons\n    frac = remaining_cal / cal\n    gram_per_serving = bag / sv\n    return frac * gram_per_serving\n",
        # The original GSM8K answer (48) is an integer; the last conjunct
        # keeps every twin's answer in the same integer form (integral
        # grams), so the twin never trades the original's exact-match-clean
        # answer for a long fraction.
        constraints_src="def valid(**p):\n    cal, bag, sv, target, cons = (p['cal'], p['bag'], p['servings'],\n                                   p['target'], p['consumed'])\n    if not (cal > 0 and bag > 0 and sv > 0 and target > cons > 0\n            and (target - cons) < cal * 3):\n        return False\n    grams = (target - cons) / cal * (bag / sv)\n    return abs(grams - round(grams)) < 1e-9\n",
        original_values={'cal': 250, 'bag': 300, 'servings': 5, 'target': 2000, 'consumed': 1800},
        original_answer='48',
    ),
    TwinTemplate(
        gsm8k_index=44,
        text_template='Charlie wants to sell beeswax candles.  For every pound of beeswax, he can make {cpl} tapered candles.  One pound of beeswax and the wicks cost ${supply:.2f} in supplies.   If he sells each candle for ${price:.2f} each, what is his net profit if he makes and sells {n} candles?',
        param_names=('cpl', 'supply', 'price', 'n'),
        solve_src="def solve(**p):\n    lbs = p['n'] / p['cpl']\n    cost = lbs * p['supply']\n    revenue = p['n'] * p['price']\n    return revenue - cost\n",
        constraints_src="def valid(**p):\n    cpl, sup, pr, n = p['cpl'], p['supply'], p['price'], p['n']\n    return cpl > 0 and sup > 0 and pr > 0 and n > 0 and n % cpl == 0\n",
        original_values={'cpl': 10, 'supply': 10, 'price': 2, 'n': 20},
        original_answer='20',
    ),
    TwinTemplate(
        gsm8k_index=45,
        text_template='Meredith is a freelance blogger who writes about health topics and submits to clients each day as her permanent job. A blog article takes an average of {hours} hours to research and write about. Last week, she wrote {monday} articles on Monday and  {fnum}/{fden} times more articles on Tuesday than on Monday. On Wednesday, she wrote twice the number of articles she wrote on Tuesday. Calculate the total number of hours she spent writing articles in the three days.',
        param_names=('hours', 'monday', 'fnum', 'fden'),
        solve_src="def solve(**p):\n    hours, monday, fn, fd = p['hours'], p['monday'], p['fnum'], p['fden']\n    tue_extra = fn / fd * monday\n    tuesday = monday + tue_extra\n    wednesday = 2 * tuesday\n    return (monday + tuesday + wednesday) * hours\n",
        constraints_src="def valid(**p):\n    hours, monday, fn, fd = p['hours'], p['monday'], p['fnum'], p['fden']\n    return (hours > 0 and monday > 0 and fn > 0 and fd > 0\n            and (monday * fn) % fd == 0)\n",
        original_values={'hours': 4, 'monday': 5, 'fnum': 2, 'fden': 5},
        original_answer='104',
    ),
    TwinTemplate(
        gsm8k_index=46,
        text_template='Candice put {initial} post-it notes in her purse before she headed out to her job at the coffee shop.  On her way, she stopped off at the store and purchased a package of Post-it notes;  At work, she placed a single Post-it note on each of {used} different cups of coffee.  If she had {remaining} post-it notes remaining overall, how many Post-it notes were in the package that she purchased?',
        param_names=('initial', 'used', 'remaining'),
        solve_src="def solve(**p):\n    return p['used'] + p['remaining'] - p['initial']\n",
        constraints_src="def valid(**p):\n    i, u, r = p['initial'], p['used'], p['remaining']\n    return i > 0 and u > 0 and r > 0 and (u + r - i) > 0\n",
        original_values={'initial': 80, 'used': 220, 'remaining': 23},
        original_answer='163',
    ),
    TwinTemplate(
        gsm8k_index=47,
        text_template='John buys twice as many red ties as blue ties.  The red ties cost {pct}% more than blue ties.  He spent ${spent} on blue ties that cost ${price} each. How much did he spend on ties?',
        param_names=('pct', 'spent', 'price'),
        solve_src="def solve(**p):\n    pct, spent, price = p['pct'], p['spent'], p['price']\n    blue_n = spent / price\n    red_n = 2 * blue_n\n    red_price = price * (1 + pct / 100)\n    return spent + red_n * red_price\n",
        constraints_src="def valid(**p):\n    pct, spent, price = p['pct'], p['spent'], p['price']\n    return (pct > 0 and spent > 0 and price > 0 and spent % price == 0\n            and (price * pct) % 100 == 0)\n",
        original_values={'pct': 50, 'spent': 200, 'price': 40},
        original_answer='800',
    ),
    TwinTemplate(
        gsm8k_index=48,
        text_template='Tracy used a piece of wire {feet} feet long to support tomato plants in the garden. The wire was cut into pieces {inches} inches long. How many pieces did she obtain?',
        param_names=('feet', 'inches'),
        solve_src="def solve(**p):\n    total_inches = p['feet'] * 12\n    return total_inches / p['inches']\n",
        constraints_src="def valid(**p):\n    f, i = p['feet'], p['inches']\n    return f > 0 and i > 0 and (f * 12) % i == 0\n",
        original_values={'feet': 4, 'inches': 6},
        original_answer='8',
    ),
    TwinTemplate(
        gsm8k_index=49,
        text_template="Richard lives in an apartment building with {floors} floors. Each floor contains {upf} units, and {onum}/{oden} of the building is occupied. What's the total number of unoccupied units In the building?",
        param_names=('floors', 'upf', 'onum', 'oden'),
        solve_src="def solve(**p):\n    fl, upf, on, od = p['floors'], p['upf'], p['onum'], p['oden']\n    total = fl * upf\n    occupied = total * on / od\n    return total - occupied\n",
        constraints_src="def valid(**p):\n    fl, upf, on, od = p['floors'], p['upf'], p['onum'], p['oden']\n    total = fl * upf\n    return fl > 0 and upf > 0 and on > 0 and od > 0 and (total * on) % od == 0\n",
        original_values={'floors': 15, 'upf': 8, 'onum': 3, 'oden': 4},
        original_answer='30',
    ),
    TwinTemplate(
        gsm8k_index=50,
        text_template='Lloyd has an egg farm. His chickens produce {eggs} eggs per day and he sells them for ${price} per dozen. How much does Lloyd make on eggs per week?',
        param_names=('eggs', 'price'),
        solve_src="def solve(**p):\n    weekly = p['eggs'] * 7\n    dozens = weekly / 12\n    return dozens * p['price']\n",
        constraints_src="def valid(**p):\n    e, pr = p['eggs'], p['price']\n    return e > 0 and pr > 0 and (e * 7) % 12 == 0\n",
        original_values={'eggs': 252, 'price': 2},
        original_answer='294',
    ),
)

SKIPPED_ITEMS: tuple[tuple[int, str], ...] = (
    (8, "multi-stage narrative mixes spelled-word durations ('half-hour') with digit durations that must stay grammatically singular/plural; too fragile to parametrize safely"),
    (12, "break-even year count relies on an exact float division (cost / annual profit) plus a +1 'starts earning next year' step; keeping that exact under resampling needs float-tolerant constraints that are too fragile for the generic numeric resampler"),
    (38, "solution logic references implicit 'days he doesn't run' derived from a 7-day week that is never stated as a digit or explicit constant in the problem text; can't be re-derived generically from parametrized text"),
    (40, "both multipliers ('four times', 'two times') are spelled words and the single free digit (Suzy's age = 1) can't vary without breaking singular/plural agreement in 'is 1 year old'; not enough resamplable freedom to be a meaningful twin"),
)
